---
<<<<<<< HEAD
- name: 1 - Common & Prerequisites
=======
# ==============================================================================
# PHASE 1 : Common & Prerequisites
# ==============================================================================

- name: Common & Prerequisites
>>>>>>> feat/ansible
  hosts: all
  become: yes  # "root" (sudo)

  tasks:
    - name: Mettre à jour le cache APT et faire un upgrade complet
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Utilitaires d'administration
      apt:
        name:
          - htop
          - curl
          - git
          - tree
          - bash-completion
          - cron
        state: present

    - name: Fuseau horaire correct (Europe/Paris)
      timezone:
        name: Europe/Paris

- name: Prérequis spécifiques au Monitoring
  hosts: vm-monitor
  become: yes

  tasks:
    - name: Installer Docker et le plugin Compose
      ansible.builtin.apt:  
        name: 
          - docker.io
          - docker-compose
        state: present
        update_cache: yes