# inventory.ini

[routers]
vm-fw

[bastions]
vm-bastion

[dmz]
vm-proxy

[production]
vm-prod

[management]
vm-backup
vm-monitor

# --- Virtual gorups ---
# all without router vm (NTP, DNS, etc.)
[clients:children]
bastions
dmz
production
management