[router]
vm-fw ansible_host=192.168.150.11

[bastion]
# Le bastion est exposé sur le port 2222 de l'IP publique
vm-bastion ansible_host=192.168.150.11 ansible_port=2222

[prod]
vm-prod ansible_host=172.16.30.10

[proxy]
vm-proxy ansible_host=172.16.20.10

[backup]
vm-backup ansible_host=172.16.40.10

[monitor]
vm-monitor ansible_host=172.16.50.10

# Le groupe du réseau interne (TOUT sauf le pare-feu et le bastion)
[internal_network:children]
prod
proxy
backup
monitor

# La magie du rebond simple
[internal_network:vars]
ansible_ssh_common_args='-o ProxyJump="debian@192.168.150.11:2222" -o StrictHostKeyChecking=no'

[all:vars]
ansible_user=debian
ansible_ssh_private_key_file=~/.ssh/id_ed25519